version: '3.8'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./etc/.htpasswd
              target: /usr/local/apache2/.htpasswd
        environment:
            SSL: no
