version: '3.7'

services:

    httpd:
        image: ghcr.io/minjja/webdav
        secrets:
            - source: htpasswd
              target: /usr/local/apache2/.htpasswd
            - source: key.pem
              target: /usr/local/apache2/ssl/key.pem
            - source: cert.pem
              target: /usr/local/apache2/ssl/cert.pem
        volumes:
            - type: volume
              source: webdav
              target: /usr/local/apache2/webdav

volumes:
    webdav:

secrets:
    htpasswd:
        external: true
    key.pem:
        external: true
    cert.pem:
        external: true
