version: '3.7'

services:

    app:
        image: ghcr.io/minjja/webdav
        secrets:
            - source: htpasswd
              target: /etc/apache2/.htpasswd
        volumes:
            - type: volume
              source: html
              target: /var/www/html

volumes:
    html:

secrets:
    htpasswd:
        external: true
