version: '3.8'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: .htpasswd
              target: /usr/local/apache2/.htpasswd
