version: '3.7'

services:

    app:
        image: ghcr.io/minjja/webdav
        secrets:
            - source: htpasswd
              target: /etc/apache2/.htpasswd
        volumes:
            - type: volume
              source: webdav
              target: /var/www/webdav

volumes:
    webdav:

secrets:
    htpasswd:
        external: true
