version: '3.7'

services:

    app:
        image: k3vmcd/webdav
        ports:
            - 443:443
        volumes:
            - type: volume
              source: media
              target: /var/lib/dav
        secrets:
            - source: htpasswd
              target: /user.passwd
        environment:
            AUTH_TYPE: Basic
            SSL_CERT: selfsigned
            SERVER_NAMES: webdav.cloud.cherryservers.net

volumes:
    media:

secrets:
    htpasswd:
        external: true
